warehouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      port: 8443
      username: default
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: true
    ci:
      type: clickhouse
      schema: default
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      port: 8443
      username: default
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: true
